### ISSUE TITLE
Simplify dark comparison

### ISSUE THREAD

**Issue by ericvaandering** [piperov/Rucio_storage_consistency#1]
Looking at https://github.com/piperov/Rucio_storage_consistency/blob/master/deckard/cmp2dark.py it looks over complicated to me (and has unusable code paths) so I suspect you copied it from Igor's code base. 

I think you can simplify this down to 10 lines at most: open both files, use readlines() to populate two python sets of files, and take the intersection between the two sets.

IF you know from the statistics files that there are too many dark files to operate on, you shouldn't have to worry about memory issues because you'd never call this function for large files, right?

**Comment by ericvaandering** [comment]
This would have the side benefit of clearing up a lot of the unneeded dependencies we talked about.

**Comment by piperov** [comment]
That's correct - I used the cmp2.py function developed by Igor for the scanner, as it looked like a useful piece. 
I agree it's an overkill and introduces unnecessary dependencies.

Will clean up and simplify.

**Comment by piperov** [comment]
Partitioned List use was completely removed from the code, and replaced with simple set comparison.
